name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker build . --file Dockerfile --tag ramona84/sec-tests:latest
    - uses: anchore/scan-action@v1
      with:
        image-reference: "ramona84/sec-tests:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: true
